### ISSUE TITLE
Không thêm mới/thay đổi được chuyên mục của Module Tin tức

### ISSUE THREAD

**Issue by yeunukeviet** [nukeviet/update#10]
Tôi đã báo lỗi tiếp vào đây: https://github.com/nukeviet/update/issues/8 , nhưng sau 1 ngày không ai lên tiếng nên tôi mở báo lỗi mới này.

Xin cảm ơn hoaquynhtim99 đã gợi ý hướng khắc phục.

Cuối cùng thì tôi đã làm theo gợi ý thứ 2 của hoaquynhtim99 là cài đặt mới một bản NV 4.0.28 rồi tự mình nâng cấp CSDL theo ghi chú phát triển ở https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.0.28.

Đã vào được quản trị để đăng bài mới. Tuy nhiên có mấy lỗi sau:

```
Lỗi của module Tài khoản
    Các tài khoản thành viên còn nguyên nhưng các nhóm thành viên mới do tôi tạo ra đều biến mất.
    Chỉ còn lại những nhóm thành viên có sẵn ngay khi cài đặt, nhưng tất cả đều bằng tiếng Anh, như: Super admin, General admin,New Users,...

Lỗi của module Tin tức: Đã đăng được bài mới nhưng không thêm mới hoặc sửa đổi được chuyên mục  (kể cả module ảo của news)
```

Các báo lỗi  như sau:

```
Nên chú ý: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ad_block_cat' in 'field list'
Lỗi hệ thống không cập nhật được nội dung, bạn hãy kiểm tra lại liên kết tĩnh tiêu đề bài viết có thể bị trùng (thực tế không trùng)

Nên chú ý: Undefined index: ad_block_cat in file /modules/news/theme.php on line 357
```

Tôi mở tệp theme.php, tìm thấy dòng code 357:
$array_row_i['ad_block_cat'] = explode(',', $array_row_i['ad_block_cat']);

```
Nên chú ý: Undefined index: ad_block_cat in file /modules/news/admin/cat.php on line 58
```

Tìm thấy dòng code 58:
$ad_block_cat = $global_array_cat[$catid]['ad_block_cat'];

Lỗi 1 chưa cần sửa vội nhưng lỗi 2 cần được sửa ngay.

Rất mong Ban quản trị và đội code cho hướng dẫn khắc phục sớm.

Tôi xin cảm ơn trước.
Yeunukeviet.

**Comment by hoaquynhtim99** [comment]
Mình xin trả lời vắn tắt như sau:

Đối với module users mất nhóm bạn kiểm tra lại bước 

``` sql
RENAME TABLE  nv4_groups TO  nv4_users_groups;
RENAME TABLE  nv4_groups_users TO  nv4_users_groups_users;
```

Có nghĩa đổi tên bảng nv4_groups thành nv4_users_groups và nv4_groups_users thành nv4_users_groups_users. Vậy bạn kiểm tra lại bảng nv4_users_groups, nv4_users_groups_users có tồn tại không và có dữ liệu không.

Lỗi module news của bạn do chưa thực hiện được ngay bước đầu tiên: Cập nhật CSDL cho module news: Tính năng Add top and bottom block of Category

``` php
// Duyệt tất cả các ngôn ngữ
$language_query = $db->query('SELECT lang FROM ' . $db_config['prefix'] . '_setup_language WHERE setup = 1');
while (list ($lang) = $language_query->fetch(3)) 
{
    // Lấy tất cả các module và module ảo của nó
    $mquery = $db->query("SELECT title, module_data FROM " . $db_config['prefix'] . "_" . $lang . "_modules WHERE module_file = 'news'");
    while (list ($mod, $mod_data) = $mquery->fetch(3)) 
    {
        try 
        {
            $db->query("ALTER TABLE " . $db_config['prefix'] . "_" . $lang . "_" . $mod_data . "_cat ADD `ad_block_cat` varchar(250) NOT NULL default '' AFTER `featured`");
        } 
        catch (PDOException $e) 
        {
            //
        }
    }
}
```

Trong đoạn code trên có thêm trường ad_block_cat vào bảng cat, báo lỗi của bạn chỉ ra rằng không tồn tại trường ad_block_cat tức là bạn chưa thực hiện được bước đó.

**Comment by vuthao** [comment]
Mình kiểm tra nâng cấp từ bản RC2 lên RC3 không bị lỗi như của bạn. Nên nếu bạn nào bị lỗi nâng cấp thử công
