### ISSUE TITLE
Lỗi upgrade module user từ 4.0.27 lên 4.0.28

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/update#11]
Lỗi nâng cấp module user từ bản 4.0.27 lên 4.0.28
![error](https://cloud.githubusercontent.com/assets/9360175/15381282/5f56e052-1da8-11e6-9b94-ab097bad6ed0.png)

**Comment by vuthao** [comment]
Mình đang kiểm tra và fix lỗi này.

**Comment by vuthao** [comment]
Lỗi trên đã được sửa, các bạn tải lại gói cập nhật nhé.
