### ISSUE TITLE
Google map mờ và bị treo 

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/update#13]
Khi click chuột vào địa chỉ Google map xuất hiện nhưng mờ và bị treo. 
Mình click chuột ra ngoài để thoát nhưng không được. Muốn thoát phải nhấn F5.
Mình nâng cấp từ 4.0.28 lên 4.0.29 trên localhost

**Comment by vuthao** [comment]
Bạn thử xóa cache của trình duyệt xem sao. Tôi thử trên local và site đều bình thường.

Demo: https://mangvn.com/

**Comment by duongGitHub** [comment]
Cám ơn bác, sáng dậy kiểm tra lại thì thấy nó chạy bình thường mặt dù mình chưa xóa cache trình duyệt không hiểu tại sao? Nhưng sao khi chuyển sang giao diện Mobile thì Map chỉ bản đồ của Nukeviet chỗ đường Lương Ngọc Quyên. Mình đã download 3 file mới nhất về mà vẫn vậy?
