### ISSUE TITLE
Lỗi trùng trùng key tags_id khi nâng cấp news từ 3.4 lên 4.0.29

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/update#14]
<b>Notice</b>:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-1' for key 'id_tid' in

**Comment by vuthao** [comment]
Nếu nâng cấp từ bản 3.4 lên bản 4 vui lòng đăng tại đây: https://github.com/nukeviet/module_c34to40/issues
