### ISSUE TITLE
Lỗi tool nâng cấp từ 26 lên 27

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/update#15]
Khi thực hiện nâng cấp bị lỗi "GET /install/update.php?step=2&substep=3&load=nv_up_finish
500 Internal Server Error
119ms  
"

Không thể nâng cấp csdl
![untitled-1](https://cloud.githubusercontent.com/assets/13896524/15642287/80d769ce-2670-11e6-9a81-0a514b0ac69f.jpg)

**Comment by ThinhNguyenVB** [comment]
Nguyên nhân lỗi ở 2 câu inser cuối của phần nv.._finish do nó có sẵn dữ liệu

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/update/commit/ed14c55c9d5a59b08237ebd42989e359a6c56e9e
