### ISSUE TITLE
Website không hoạt động sau khi nâng cấp

### ISSUE THREAD

**Issue by vandien** [nukeviet/update#16]
Mình đã cập nhật thành công website tgktrans.com lên phiên bản mới nhất theo các hướng dẫn. Tuy nhiên, sau khi cập nhật thì website lại không truy cập được trang chủ (mặc dù trang quản trị vẫn vào bình thường).

Thông báo lỗi như sau:

> Trang tgktrans.com hiện không hoạt động
> tgktrans.com hiện không thể xử lý yêu cầu này.
> HTTP ERROR 500

Xin được hướng dẫn khắc phục lỗi.
Trân trọng cảm ơn.

**Comment by hoaquynhtim99** [comment]
Bạn kiểm tra lại tương thích module bạn dùng làm trang chủ và các block bạn đặt trên trang chủ nhé

**Comment by vandien** [comment]
Vâng. Mình đã khắc phục được, nguyên nhân do lỗi từ module contact. Nhưng giờ lại mất chức năng bật kéo thả block. Không hiểu tại sao.
