### ISSUE TITLE
Lỗi module Photos sau khi nâng cấp (504 Gateway Timeout)

### ISSUE THREAD

**Issue by lhanh1981** [nukeviet/update#17]
Mình không thấy có bảng nào tên *_site_cat trong CSDL, sao lại có đoạn code select bảng này trong file vmodule.php? 
`$array_site_cat_module = array();if ($global_config['idsite']) {    $_module = $db->query('SELECT module FROM ' . $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_site_cat t1 INNER JOIN ' . $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_site t2 ON t1.cid=t2.cid WHERE t2.idsite=' . $global_config['idsite'])->fetchColumn();    if (! empty($_module)) {        $array_site_cat_module = explode(',', $_module);    }}`

Sau khi upgrade lên V4.1 thì hỏng module Photos, không tạo được album ảnh, mỗi khi upload ảnh xong nhấn nút save đều bị báo lỗi lỗi "504 Gateway Timeout", mặc dù V4.0 chạy bình thường :(

**Comment by hoaquynhtim99** [comment]
Chào bạn, module photo bạn có thể thực hiện các hướng dẫn sau để nâng cấp lên tương thích bản 4.1 https://github.com/nukeviet/update/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-n%C3%A2ng-c%E1%BA%A5p-module-t%C6%B0%C6%A1ng-th%C3%ADch-b%E1%BA%A3n-4.0.29-l%C3%AAn-4.1.00, còn đoạn code bạn gửi không liên quan đến lỗi bạn gặp phải
