### ISSUE TITLE
Phiên bản beta 1 có lỗi khi đăng ký thành viên mới ở ngoài trang chủ

### ISSUE THREAD

**Issue by saurom1205** [nukeviet/update#19]
Phiên bản beta 1 có lỗi khi đăng ký thành viên mới ở ngoài trang chủ
- Sau khi vào Thành viên - Đăng ký- Điền đầy đủ thông tin rùi submit thì nó chuyển trang. 
Trong quá trình chuyển trang thông báo lỗi như sau

/","mess":"\u0110\u0103ng k\u00fd t\u00e0i kho\u1ea3n th\u00e0nh c\u00f4ng","redirect":""}

Cẩn sử lý như thế nào và ở đâu ?

**Comment by hoaquynhtim99** [comment]
Hiện bản beta 2 đã phát hành bạn nâng cấp lên bản mới nhé
