### ISSUE TITLE
Lỗi nâng cấp lên phiên bản nukeviet 4.1

### ISSUE THREAD

**Issue by nvnghiem** [nukeviet/update#25]
mình tiến hành nâng cấp từ bản 4.0.29 lên bản mới nhất. mọi thứ đều ổn cho đến công đoạn Thêm module xác thực hai bước thì dừng lại. xin được trợ giúp. thanks.

**Comment by hoaquynhtim99** [comment]
Bạn khôi phục lại site, dọn dẹp hệ thống sau đó tiến hành nâng cấp, nếu lỗi, gửi nội dung file trong thư mục data/logs/error_logs/ lên đây để kiểm tra

**Comment by hoaquynhtim99** [comment]
Mình check lại thấy lịch sử của bạn là Nâng cấp 4.0.25 lên 4.0.27 sao giờ là 4.0.29 lên 4.1.02 nhỉ, bạn kiểm tra lại kỹ vấn đề này giúp

**Comment by nvnghiem** [comment]
Vâng. Mình nâng cấp từ 4.0.25 lên 4.0.27, sau đó lên 4.0.29 và từ 4.0.29
lên 4.1
Không biết trong quá trình nâng cấp có lỗi gì không mà hiện tại không thể
tiếp tục nâng cấp lên được. Để e gửi a ftp a rảnh thì kiểm tra giúp e với
ạ. E cảm ơn nhiều.

Vào 25-04-2017 10:38, "Tan Dung Phan" <notifications@github.com> đã viết:

**Comment by hoaquynhtim99** [comment]
Bạn post vấn đề này trên diễn đàn sau đó gửi link bài viết và thông tin FTP, quản trị site mình kiểm tra nhé hộp thư: dungpt a còng vinades chấm vi en. Mình xin đóng issue này lại.
