### ISSUE TITLE
Thêm kiểm tra cấu hình trước khi nâng cấp

### ISSUE THREAD

**Issue by vuthao** [nukeviet/update#26]
Cần Thêm bước kiểm tra cấu hình trước khi nâng cấp.

Ví dụ nâng cấp từ bản 4.0.29 lên bản 4.1 thì cần thêm thư viện openssl, nhưng quá trình nâng cấp không kiểm tra, dẫn đến lỗi tại bước chuyển đổi mật khẩu

Do đó cần viết lại bước này cho các lần sau (Cần viết để sử dụng chung với lúc kiểm tra lúc cài đặt để không phải viết code này nhiều, và tránh vị quên)

**Comment by hoaquynhtim99** [comment]
Đã thêm ở https://github.com/hoaquynhtim99/nukeviet/commit/727dc8e951ada6f22d4cf3294e1c79924f52cacb sẽ có hiệu lực sau khi nâng cấp lên 4.2.01 về sau
