### ISSUE TITLE
Lỗi thêm nhân viên hỗ trợ trong module Contact

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/update#27]
Lỗi trắng trang khi thêm nhân viên hỗ trợ trong module Contact sau khi nâng cấp từ bản 4.1.02 lên 4.2.00

**Comment by nambmtk1993** [comment]
[04-08-2017_error_log.zip](https://github.com/nukeviet/update/files/1199719/04-08-2017_error_log.zip)
Gửi bạn file error_log. Để tiện kiểm tra lỗi

**Comment by hoaquynhtim99** [comment]
Thanks Nam nhé, lỗi đã được fix ở đây https://github.com/hoaquynhtim99/nukeviet/commit/05f3e5db84e6b7396df22eeed59f4e02fb5622c5
