### ISSUE TITLE
Lỗi không link tới được module Contact ở bên ngoài site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/update#28]
Hiện tại nếu sau khi kích hoạt đa ngôn ngữ. Mà để mặc định là Ngôn ngữ không hiển thị ngoài site. Sau đó ra ngoài trang chủ không thể link vào nội dung contact của website. 

Cả 2 ngôn ngữ Anh và Pháp đều bị

**Comment by hoaquynhtim99** [comment]
@nambmtk1993 Nếu không cho hiển thị ngoài site thì sẽ không thể xem module nào là đúng mà có gì sai đâu nhỉ.

**Comment by nambmtk1993** [comment]
@hoaquynhtim99 nhưng với quản trị tối cao thì phải được xem chứ. Xin lỗi vì em chưa nói. Quyền xem ở đây là quyền quản trị tối cao

**Comment by hoaquynhtim99** [comment]
Thanks Nam, cái này đã fix https://github.com/hoaquynhtim99/nukeviet/commit/5e09328fb724e1e21d954f5fa3709d8d05ee2c4f
