### ISSUE TITLE
Lỗi chưa dịch hết lang module Banner

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/update#29]
Lỗi chưa dịch hết lang module Banner sang ngôn ngữ Tiếng Anh và Pháp
![error_banner](https://user-images.githubusercontent.com/9360175/28932341-5837d07c-78a3-11e7-9494-e631069013cd.png)

**Comment by hoaquynhtim99** [comment]
@nambmtk1993 bản dev chưa đủ lang nha Nam, khi nào phát hành sẽ dịch bổ sung
