### ISSUE TITLE
Lỗi sau khi cài 4.0.27

### ISSUE THREAD

**Issue by doanhauhpfc** [nukeviet/update#3]
- Bản RC1, chạy nâng cấp lên 4.0.26 --- 4.0.27
- ĐÃ tiến hành các bước xóa cache như hướng dẫn 4.0.27
- Trang chủ báo lỗi:
  Nên chú ý Nên chú ý: Undefined offset: 0 in file /modules/news/theme.php on line 449

**Comment by vuthao** [comment]
Bản NukeViet 4.0.27 chúng tôi vẫn chưa thông báo phát hành bạn. Vẫn đang trong quá trình hoàn thiện.

**Comment by vuthao** [comment]
Lỗi này đã được cập nhật.
