### ISSUE TITLE
Lỗi khi tiến hành update từ 4.2 lên 4.3

### ISSUE THREAD

**Issue by oantuti** [nukeviet/update#31]
Mình đính kèm các file log.
Trong file log của data_logs thì báo đã thành công hết, nhưng file log errors_logs lại báo lỗi 
[Warning(2): require(C:/inetpub/wwwroot/includes/language/vi/functions.php): failed to open stream: No such file or directory] [FILE: /includes/mainfile.php] [LINE: 172]
[13-11-2017_error_log.log](https://github.com/nukeviet/update/files/1465489/13-11-2017_error_log.log)
[12-11-2017_error_log.log](https://github.com/nukeviet/update/files/1465490/12-11-2017_error_log.log)
[log-update-17-16-41-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log](https://github.com/nukeviet/update/files/1465493/log-update-17-16-41-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log)
[log-update-17-16-37-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log](https://github.com/nukeviet/update/files/1465494/log-update-17-16-37-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log)

**Comment by vuthao** [comment]
@oantuti bạn cần mởi từng file để ra xem nó lỗi ghì để sửa lại nhé.

ví dụ 2 file
log-update-17-16-41-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log
log-update-17-16-37-12-11-2017-4a44f92f0784bbea1c5eadb2535e9c88.log
Nó chỉ là lưu trạng thái quá trình nâwng cấp, cái nem xong có thể xóa.

File 13-11-2017_error_log.log hầu hết là lỗi:
[Mon, 13 Nov 2017 05:13:35 +0700] [capnuocbaclieu.com.vn] [203.113.152.7] [Warning(2): require(C:/inetpub/wwwroot/includes/language/vi/functions.php): failed to open stream: No such file or directory] [FILE: 

Nhiều khả năng hệ thống không đọc được file includes/language/vi/functions.php, kiểu tra lại nếu ko có file này cần copy thêm file này.

**Comment by hoaquynhtim99** [comment]
Tra file log site của bạn có hai vấn đề:
1. File config thiếu dòng `$global_config['cached'] = 'files';` vấn đề này xảy ra khi nâng cấp lên 4.0.24 chưa đúng quy trình, xem lại hướng dẫn https://github.com/nukeviet/update/tree/to-4.0.24#1-cập-nhật-file-configphp
2. Lỗi đối với `vi/functions.php` file này xuất hiện khi nâng cấp lên 4.2.01 https://github.com/nukeviet/update/blob/to-4.2.01/install/update/includes/language/vi/functions.php site của bạn thiếu tức quá trình nâng cấp đã bị sót file. Đơn giản hãy lấy file tương ứng từ bản cài đặt nukeviet 4.3.00 upload lên hosting
