### ISSUE TITLE
Bổ sung $global_config['upload_chunk_size']=0; vào config_global.php khi nâng cấp từ 4.3.00 lên 4.3.04

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/update#33]
e nâng cấp từ 4.3.00 lên 4.3.04 không cập nhật dòng $global_config['upload_chunk_size']=0; vào file config_global.php. Đội code kiểm tra lại và cập nhật dòng này vào file khi nâng cấp nhé. thiếu dòng này thì cái upload bị lỗi

**Comment by hoaquynhtim99** [comment]
`$global_config['upload_chunk_size']` là giá trị được thêm vào ở NukeViet 4.3.00.
Gói cập nhật từ 4.2.01, 4.2.02, 4.2.03 lên 4.3.00 sẽ có, tất nhiên là 4.3.00 lên 4.3.04 không có nó

**Comment by webvangvn** [comment]
lúc trước cài mới 4.3.00 mà, sau đó mới update lên 4.3.04, chứ đâu có update từ phiên bản 4.2.x đâu.

**Comment by hoaquynhtim99** [comment]
@webvangvn đây là nội dung của file cài đặt tại tree 4.3.00  https://github.com/nukeviet/nukeviet/blob/4.3.00/install/data.php#L96
Đây là nội dung gói cập nhật lên 4.3.00 https://github.com/nukeviet/update/blob/to-4.3.00/install/update_data.php#L370

Có thể thấy cả bản cài đặt và gói cập nhật đều có thông số đó
