### ISSUE TITLE
Lỗi nâng cấp lên bản NukeViet 4.4

### ISSUE THREAD

**Issue by vuthao** [nukeviet/update#35]
1) chưa có hướng dẫn xóa logo dạng swf ví dụ giao diện egov, mobile_egov

**Comment by vuthao** [comment]
2. Tong hướng dẫn có sửa các đoạn Sửa lỗi giao diện block global.login.php và global.user_button.php
Nhưng việc này chưa sửa trong giao diện mobile_default
3. Có cấu hình cho BLOCK_JS, không thấy cấu hình cho CSS theme mobile_default

**Comment by hoaquynhtim99** [comment]
@vuthao 

> chưa có hướng dẫn xóa logo dạng swf ví dụ giao diện egov, mobile_egov

Cái này không cần thiết phải xóa, giao diện để logo hay banner bằng swf vẫn hoạt động, trong admin vẫn có thể chọn file bất kỳ làm logo. Chỉ có khác giao diện mặc định sẽ xử lý và xuất ra dạng image, còn giao diện khác vẫn sẽ xuất ra swf (do file theme.php của giao diện điều khiển).

> Tong hướng dẫn có sửa các đoạn Sửa lỗi giao diện block global.login.php và global.user_button.php Nhưng việc này chưa sửa trong giao diện mobile_default

Mobile_default đã sửa, có lẽ a xem nhầm https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/themes/mobile_default/modules/users/block.user_button.tpl#L26

> Có cấu hình cho BLOCK_JS, không thấy cấu hình cho CSS theme mobile_default

CSS đã được gọi trực tiếp qua biến `$my_head`

**Comment by NukeVlad** [comment]
Trong tệp cập nhật / cài đặt / cập nhật / mô-đun / người dùng / ngôn ngữ / admin_vi.php, bạn cần thay thế các ký tự ở nhiều vị trí trong văn bản " - '.
В файле update/install/update/modules/users/language/admin_vi.php нужно во многих местах текста заменить знак " на знак '.

**Comment by hoaquynhtim99** [comment]
@NukeVlad fixed https://github.com/nukeviet/nukeviet/commit/9761ac34ad67a2daf0a86297b90c8b879e45d4c3
