### ISSUE TITLE
Lỗi hiện thị các icon chức năng của khung Editor

### ISSUE THREAD

**Issue by doanhauhpfc** [nukeviet/update#4]
Cụ thể:

Icon Canh trái : hiển thị Canh giữa
Icon Canh đều : hiển thị mặt cười

http://s21.postimg.org/hg0hs45g7/edit.png

**Comment by vuthao** [comment]
@doanhauhpfc bạn xem lại quy định báo lỗi tại đây nhé:
https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by timacleo** [comment]
Tôi cũng bị gặp trường hợp tương tự
