### ISSUE TITLE
Lỗi block_newscenter

### ISSUE THREAD

**Issue by favouritekid** [nukeviet/update#5]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: length_othertitle in file /modules/news/blocks/module.block_newscenter.php on line 181
![image](https://cloud.githubusercontent.com/assets/9113677/13315914/1982672c-dbe0-11e5-9849-3ec404918865.png)

**Comment by vuthao** [comment]
Bạn bật kéo thả block lên, và cấu hình lại block newscenter
