### ISSUE TITLE
[News Nukeviet 4RC2]Không bình luận được trên giao diện điện thoại

### ISSUE THREAD

**Issue by timacleo** [nukeviet/update#6]
Mình đã thử bình luận khi lựa chọn giao diện điện điện thoại và cả khi truy cập bằng điện thoại, đều không thể bình luận được.

![err](https://cloud.githubusercontent.com/assets/17309352/13370521/7188a456-dd3c-11e5-9f85-73656a7feb53.png)

Ngoài ra không thể thực hiện được thao tác trên giao diện điện thoại như xóa bình luận, thích bình luận, không thích bình luận,...

**Comment by hoaquynhtim99** [comment]
Vấn đề này đã được xử lý ở https://github.com/nukeviet/nukeviet/issues/1899
