### ISSUE TITLE
Thành viên được phân quyền không đăng được bài

### ISSUE THREAD

**Issue by SaoThe** [nukeviet/update#66]
Mình nâng cấp web lên 4.4 thì thành viên được phân quyền vẫn đăng bài được như bình thường
Khi nâng cấp lên 4.5 và cũng đã nâng cấp lên 4.5.01 chạy trên localhost thì thành viên được phân quyền vẫn đăng nhập và viết bài được nhưng đưa lên hoting thì thành viên được phân quyền viết bài trong Tin tức cũng như tất cả các thành viên được phân quyền khác cũng bị tương tự. Cụ thể là sau khi đăng nhập không nhìn thấy memu Tin tức trong admin.

**Comment by hoaquynhtim99** [comment]
Cái này bạn kiểm tra lại thao tác đưa lên site thôi chứ môi trường không làm thay đổi hoặc hỏng tính năng đó được.
Cần sự trợ giúp thêm bạn thảo luận ở https://www.facebook.com/groups/nukeviet/

**Comment by SaoThe** [comment]
Mình cũng thấy khó hiểu. Chạy từ khi 3.x đến giờ mới bị pha như này, Cập nhật trực tiếp trên hoting, xóa sạch up lại nhiều lần vẫn thế thế mới đau.

**Comment by SaoThe** [comment]
Và bây giờ thì mình đưa nguyên bộ cài gốc lên hoting thì sau khi đăng ký thêm thành viên và phân quyền quản trị cũng vẫn thế, nếu phân quyền "Điều hành chung" thì mới nhìn thấy menu dọc trong admin. mà phân quyền như thế này thì có phải ai cũng được giao quyền này đâu.
Mong được hỗ trợ.

**Comment by hoaquynhtim99** [comment]
Bạn gửi mô tả lên đây xem https://www.facebook.com/groups/nukeviet có gì mình ultraview xem thử

**Comment by SaoThe** [comment]
Cảm ơn bạn trước. Mình vừa mô tả tại https://www.facebook.com/groups/nukeviet

**Comment by hoaquynhtim99** [comment]
Phần này mình đã xử lý và chuyển sang issue cho kho NukeViet https://github.com/nukeviet/nukeviet/issues/3367
