### ISSUE TITLE
Không thể nâng cấp do không tương thích phiên bản

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/update#67]
Hiện tại e đang ở bản 4.5.00 OpenBeta 1 khi nâng cấp thủ công thì báo lỗi Không thể nâng cấp do không tương thích phiên bản. Em làm thế nào để khắc phục lỗi này được ạ 
![image](https://user-images.githubusercontent.com/70182883/161705348-1279b7e9-b163-41ac-a79f-9dac9eb4d356.png)

**Comment by hoaquynhtim99** [comment]
Mình không thấy phiên bản đó ở đây https://github.com/nukeviet/nukeviet/releases nên không xem được. Việc này có lẽ bạn phải nhờ những người có đủ khả năng giúp đỡ

**Comment by hades-1997** [comment]
e cài bản này khi nó đang là nhà phát triển á a. có cách nào ghi đè thay vì dùng file install không ạ

**Comment by hoaquynhtim99** [comment]
Nếu bạn dùng bản không chính thức thì có thể cập nhật theo các ghi chú ở đây https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.5 (làm ngược từ dưới lên)
