### ISSUE TITLE
lỗi không hiển thị audio sau khi nâng cấp từ 4.502

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/update#68]
sau khi e update phiên bản 4.5.02 lên 4.5.03 đã setup giọng đọc. đã thêm giọng đọc.
đã check có file upload lên, nhưng khi view bài xem thì không hiển thị thanh đọc bài
![image](https://user-images.githubusercontent.com/70182883/209758389-d9e73ae6-c4c4-451a-8221-24a5bc4a377e.png)

**Comment by hoaquynhtim99** [comment]
Phần này chắc bạn chưa cập nhật giao diện theo hướng dẫn rồi. Check [hướng dẫn](https://github.com/nukeviet/update/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-n%C3%A2ng-c%E1%BA%A5p-giao-di%E1%BB%87n-t%C6%B0%C6%A1ng-th%C3%ADch-t%E1%BB%AB-NukeViet-4.5.00-l%C3%AAn-c%C3%A1c-phi%C3%AAn-b%E1%BA%A3n-4.5-cao-h%C6%A1n)
