### ISSUE TITLE
lỗi thêm module ảo

### ISSUE THREAD

**Issue by tuanvanpham84** [nukeviet/update#7]
Sau khi nâng cấp từ 4.0.25 lên 4.0.27 , em thực hiện lệnh thêm module ảo không được: ở firefox thì nó ra trang trắng, ở cốc cốc nó bảo lỗi máy chủ 500. xin hướng dẫn em cách khắc phục

**Comment by vuthao** [comment]
bạn    vào phpMyAdmin chạy đoạn SQL sau nhé: 

``` sql
ALTER TABLE nv4_setup_extensions CHANGE `virtual` is_virtual TINYINT(1) NOT NULL DEFAULT '0';
```

Nếu đã đổi prefix của CSDL thì bạn sửa lại nv4_ cho đúng với cái của bạn.
