### ISSUE TITLE
Lỗi không upload được file trong bài viết trên Nukeviet 3.4.02.r1929

### ISSUE THREAD

**Issue by nangbuon** [nukeviet/update#72]
Không hiểu sao tự dưng mình không upload được file trong bài viết trên Nukeviet 3.4.02.r1929  và báo lỗi: "Hệ thống không thể xác định được định dạng của file tải lên".
Mong được mọi người giúp đỡ. Trân trọng!
 
![image](https://github.com/nukeviet/update/assets/169757746/ce93fd5b-d120-425f-9633-8df02fe7a64a)

**Comment by hoaquynhtim99** [comment]
Bạn vào cấu hình upload chọn kiểu kiểm tra file tải lên thấp dần đến mức "không" rồi thử lại nhé. Ngoài ra cần kiểm tra chmod, dung lượng của website, phiên bản php đã đúng chưa.

Đối với phần này bạn tìm kiếm sự hỗ trợ https://www.facebook.com/groups/nukeviet đây là phiên bản đã hết vòng đời support kĩ thuật cũng như phát triển trên trang phát triển này rồi bạn
