### ISSUE TITLE
Lỗi trang trắng sau khi upload thủ công từ 4.0.27 lên 4.0.28

### ISSUE THREAD

**Issue by yeunukeviet** [nukeviet/update#8]
Chào anh em.

Tôi đang dùng bản 4.0.27 (cài đặt mới, không sửa chữa gì, chỉ thêm module photos và video) và nâng cấp lên 4.0.28.
Tôi thử cho kiểm tra phiên bản, vì nhận được lỗi " Dữ liệu trả về không hợp chuẩn" nên không nâng cấp tự động mà đã làm thủ công như sau:
- Giải nén gói nâng cấp update-to-4.0.28.zip. Đang ở trang thái đăng nhập quản trị web, tôi quên thoát ra khỏi quản trị mà cứ thế  Upload tất cả các file trong gói update với cấu trúc của NukeViet (copy admin lên admin, module lên module...).
  Sau khi upload, quay lại quản trị thì hệ thống yêu cầu đăng nhập lại. Đăng nhập xong, hệ thống báo đăng nhập thành công, nhưng khi bấm chọn vào "Quản trị Site" thì bị trang trắng. 
  Tôi nghĩ có thể bị lỗi do mình chưa thoát khỏi quản trị trước khi upload và dự đoán nguyên nhân là do tệp  .htaccess của bản 4.0.28 đã đè lên tệp cũ gây ra lỗi, nên tôi đã ghi đè tệp .htaccess trên trang web (vừa mới copy từ gói upload), bằng tệp .htaccess của code 4.0.27 lưu trên máy, nhưng vẫn không có gì thay đổi.

Rất lạ là khi tôi vào trang chủ theo domain cũ (là nguoiviet.de) thì bị lỗi 500, không thể truy cập được, trong khi bạn đọc cho biết họ vẫn truy cập bình thường. Tôi thử truy cập bằng domain khác chạy song song, chưa khai báo trong quản trị (là congdongviet.de) thì lại được. Nhưng vào Quản trị Site bằng congdongviet.de/admin cũng bị trang trắng. Có vấn đề gì đây với bộ nhớ đệm hoặc rewrite? 
Vì chủ quan, nghĩ chỉ là từ 4.0.27 lên 4.0.28 thôi, chắc không có vấn đề gì nên tôi không backup. 

Hiện tại không có cách nào vào quản trị để đăng bài trong khi Web của chúng tôi là web tin tức nên rất cần vào được quản trị gấp. Tôi đã tìm trước khi hỏi nhưng không tìm thấy chỗ nào báo lỗi trang trắng, nên xin anh em giúp đỡ, làm sao để vào được quản trị.

Xin cảm ơn anh em trước.
Yeunukeviet

**Comment by hoaquynhtim99** [comment]
Nếu site của bạn bây giờ bị lỗi không vào được thì bạn cần phải upload đè code cũ lên lại.
Gói update đóng gói có cấu trúc như sau:

```
----install
    ----- update_data.php
    ----- update
        ----- Các files và thư mục con
```

Khi giải nén bạn cần upload theo đúng cấu trúc nghĩa là thư mục `install` đó sẽ nhập vào thư mục install trên website của bạn chứ không có nghĩa là bạn copy các file trong thư mục update ra theo đúng cấu trúc.

Bây giờ một là bạn ghi đè code cũ để site chạy lại sau đó update lại, hai là tự mình nâng cấp CSDL theo ghi chú phát triển ở https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.0.28

**Comment by yeunukeviet** [comment]
Chào anh em,

xin cảm ơn  hoaquynhtim99.
Cuối cùng thì tôi đã làm theo gợi ý thứ 2 của hoaquynhtim99 là cài đặt mới một bản NV 4.0.28 rồi tự mình nâng cấp CSDL theo ghi chú phát triển ở https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.0.28.

Đã vào được quản trị để đăng bài mới. Tuy nhiên có mấy lỗi sau:
1. Lỗi của module Tài khoản 
   - Các tài khoản thành viên còn nguyên nhưng các nhóm thành viên mới do tôi tạo ra đều biến mất.
   - Chỉ còn lại những nhóm thành viên có sẵn ngay khi cài đặt, nhưng tất cả đều bằng tiếng Anh, như: Super admin, General admin,New Users,...
2. Lỗi của module Tin tức: Đã đăng được bài mới nhưng không thêm mới hoặc sửa đổi được chuyên mục (kể cả module ảo của news)

Các báo lỗi: 
- Nên chú ý: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ad_block_cat' in 'field list' 
- Lỗi hệ thống không cập nhật được nội dung, bạn hãy kiểm tra lại liên kết tĩnh tiêu đề bài viết có thể bị trùng (thực tế không trùng)
- Nên chú ý: Undefined index: ad_block_cat in file /modules/news/theme.php on line 357

Tôi mở tệp theme.php, tìm thấy dòng code 357: 
             $array_row_i['ad_block_cat'] = explode(',', $array_row_i['ad_block_cat']);
- Nên chú ý: Undefined index: ad_block_cat in file /modules/news/admin/cat.php on line 58 

Tìm thấy dòng code 58: 
             $ad_block_cat = $global_array_cat[$catid]['ad_block_cat'];

Lỗi 1 chưa cần sửa nhưng lỗi 2 cần được sửa ngay.

Rất mong Ban quản trị và đội code cho hướng dẫn khắc phục sớm.

Tôi xin cảm ơn trước.
Yeunukeviet.
